### ISSUE TITLE
5.3打包報錯

### ISSUE THREAD

**Issue by plasticanne** [Tencent/sluaunreal#559]
**Describe the bug**
打包時報錯,  推測可能與 windows.h的 include有關

**Version**
slua 2.1.1
Ue 5.3.1
**Desktop (please complete the following information):**
 - OS: win10
 - 
**To Reproduce**
將democpp範例直接打包shipping

**Expected behavior**
```
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(48): error C2039: 'RtlCaptureStackBackTrace': is not a member of 'FWindowsPlatformStackWalk'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Windows\WindowsPlatformStackWalk.h(11): note: see declaration of 'FWindowsPlatformStackWalk'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(48): error C2660: 'RtlCaptureStackBackTrace': function does not take 2 arguments
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winnt.h(20713): note: see declaration of 'RtlCaptureStackBackTrace'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(48): note: while trying to match the argument list '(uint64 [32], unsigned __int64)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): error C2039: '_InterlockedExchange': is not a member of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Windows\WindowsPlatformAtomics.h(13): note: see declaration of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): error C2665: '_InterlockedExchange': no overloaded function could convert all the argument types
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9787): note: could be 'unsigned __int64 _InterlockedExchange(volatile unsigned __int64 *,unsigned __int64)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: 'unsigned __int64 _InterlockedExchange(volatile unsigned __int64 *,unsigned __int64)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned __int64 *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9775): note: or       'unsigned long _InterlockedExchange(volatile unsigned long *,unsigned long)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: 'unsigned long _InterlockedExchange(volatile unsigned long *,unsigned long)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9765): note: or       'unsigned int _InterlockedExchange(volatile unsigned int *,unsigned int)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: 'unsigned int _InterlockedExchange(volatile unsigned int *,unsigned int)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned int *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Microsoft\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\INCLUDE\intrin0.inl.h(175): note: or       'long _InterlockedExchange(volatile long *,long)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: 'long _InterlockedExchange(volatile long *,long)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(189): note: while trying to match the argument list '(FTypedElementRefCount *, int)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): error C2039: '_InterlockedIncrement': is not a member of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Windows\WindowsPlatformAtomics.h(13): note: see declaration of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): error C2665: '_InterlockedIncrement': no overloaded function could convert all the argument types
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9720): note: could be 'unsigned __int64 _InterlockedIncrement(volatile unsigned __int64 *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: 'unsigned __int64 _InterlockedIncrement(volatile unsigned __int64 *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned __int64 *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9708): note: or       'unsigned long _InterlockedIncrement(volatile unsigned long *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: 'unsigned long _InterlockedIncrement(volatile unsigned long *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9699): note: or       'unsigned int _InterlockedIncrement(volatile unsigned int *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: 'unsigned int _InterlockedIncrement(volatile unsigned int *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned int *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Microsoft\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\INCLUDE\intrin0.inl.h(210): note: or       'long _InterlockedIncrement(volatile long *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: 'long _InterlockedIncrement(volatile long *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(209): note: while trying to match the argument list '(FTypedElementRefCount *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): error C2039: '_InterlockedDecrement': is not a member of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Windows\WindowsPlatformAtomics.h(13): note: see declaration of 'FWindowsPlatformAtomics'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): error C2665: '_InterlockedDecrement': no overloaded function could convert all the argument types
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9752): note: could be 'unsigned __int64 _InterlockedDecrement(volatile unsigned __int64 *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: 'unsigned __int64 _InterlockedDecrement(volatile unsigned __int64 *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned __int64 *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9740): note: or       'unsigned long _InterlockedDecrement(volatile unsigned long *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: 'unsigned long _InterlockedDecrement(volatile unsigned long *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winbase.h(9731): note: or       'unsigned int _InterlockedDecrement(volatile unsigned int *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: 'unsigned int _InterlockedDecrement(volatile unsigned int *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile unsigned int *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
E:\Microsoft\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\INCLUDE\intrin0.inl.h(170): note: or       'long _InterlockedDecrement(volatile long *)'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: 'long _InterlockedDecrement(volatile long *)': cannot convert argument 1 from 'FTypedElementRefCount *' to 'volatile long *'
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
J:\Epic Games\UE_5.3\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h(224): note: while trying to match the argument list '(FTypedElementRefCount *)'
Total time in Parallel executor: 12.33 seconds
Total execution time: 15.56 seconds
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActionsAsync(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger, IActionArtifactCache actionArtifactCache) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 417
   at UnrealBuildTool.BuildMode.BuildAsync(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 801
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 411
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
```

**Comment by zjhongxian** [comment]
试试主干上的呢？

**Comment by plasticanne** [comment]
master上的也是出相同的錯誤
